apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: forex-cron-new
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: forex-cron-new
              image: gcr.io/winter-return-223922/forex_update:latest
              command: ["/home/apollo/init.sh"]
          restartPolicy: Never
